spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_data
    username: user
    password: password1!

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
springdoc:
  swagger-ui:
    config-url:
